# Generated by Django 4.2.6 on 2023-10-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_task_options_alter_task_order_with_respect_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
